server:
  port: 8888

spring:
  application:
    name: springcloudTest
  profiles:
    active:
  cloud:
    config:
      server:
        git:
          uri: C:/Users/Owner/Documents/GitHub/springcloudTest/config-repo/

